In [32]:
# Daily Challenge
import numpy as np
import random

No1

In [33]:
# Numpy
table= np.random.randint(101,size=40*50)
print(table)

[58 76 78 ... 97 42 52]


In [34]:
table=table.reshape(40,50)

In [35]:
table

array([[58, 76, 78, ..., 96, 10,  9],
       [48, 88, 85, ..., 78, 37, 24],
       [15, 98, 61, ...,  4, 22, 96],
       ...,
       [62, 62, 82, ..., 55,  3, 72],
       [61, 21, 41, ..., 52, 44, 68],
       [56, 55, 14, ..., 97, 42, 52]])

In [153]:
# python
rows, cols = (40, 50) 
table2=[] 
for i in range(cols): 
    col = [] 
    for j in range(rows): 
        col.append(random.randint(0,100)) 
    table2.append(col) 


No 2

In [156]:
# python
print(table2[3])
# numpy
print(table[3])

[98, 58, 67, 70, 74, 61, 97, 0, 42, 90, 63, 30, 81, 45, 97, 44, 12, 21, 93, 91, 23, 24, 15, 81, 99, 31, 47, 64, 1, 7, 90, 8, 72, 9, 96, 61, 50, 34, 32, 49]
[53 65  4 36  8 46  1 21 71 17  6 29 67 40 68 25 68 44 52 45 75 35 76 65
 40 97 35 30 25 76 58 53 43 61 29 35  4 56 68 61 45 32 38 87 83 56 33  4
 44 31]


No 3 

In [174]:
# numpy
table[:,2]
# python
for num in table2:
    print (num[2])



array([78, 85, 61,  4, 87, 14, 24, 53, 95, 94, 31, 40, 75, 86, 78, 22, 95,
       80, 10, 10, 50, 48, 39, 85, 68,  4, 70, 42, 24, 45, 89, 26, 43, 87,
        4, 55, 40, 82, 41, 14])

No 4

In [219]:
# python
for i in range(len(table2[-1])):
    table2[-1][i]=7
print(table2[-1])

# numpy
table[5]=7
print(table[5])



    
    
    

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7]


No 5

In [241]:
# python
for num in range(len(table2)):
    table2[num][-1]=table2[num][0]+table2[num][1]
print(table2[0])
print(table2[1])
    
# numpy
table[ :,-1]=(table[ :,0]) +(table[ :,1])


TypeError: 'int' object is not subscriptable

In [235]:
table[-1]

array([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7, 14])

In [231]:
table2[0][0]

80